name: deleteArtifact

on:
  workflow_call:

jobs:
  pushZero:
    runs-on: ubuntu-latest
    steps:
    - name: github-pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./README.md
        overwrite: true

    - name: decrypted-files
      uses: actions/upload-artifact@v4
      with:
        name: decrypted-files
        path: ./README.md
        overwrite: true

