name: deleteArtifact

on:
  workflow_call:

jobs:
  pushZero:
    steps:
    - name: github-pages
      use: actions/upload-artifact@v4
      with:
        name: github-pages
        path: README.md
        compression-level: true

    - name: decrypted-files
      use: actions/upload-artifact@v4
      with:
        name: ecrypted-files
        path: README.md
        compression-level: true

