name: main

on:
  push:
    branches:
      - main  # default branch

jobs:
  decodermd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
  trigger-pages-build:
    needs: decodermd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private actions
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Trigger pages build
        uses: ./.github/workflows/pagesBuild.yml  # 引用工作流
