name: main

on:
  push:
    branches:
      - main  # default branch

jobs:
  decodermd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
  recall pageBuild:
    needs: decodermd
    uses: ./.github/workflows/pagesBuild.yml